// @flow

export const GET_USAGE_STATISTICS_REQUEST = 'GET_USAGE_STATISTICS_REQUEST';
export const GET_USAGE_STATISTICS_SUCCESS = 'GET_USAGE_STATISTICS_SUCCESS';
export const GET_USAGE_STATISTICS_FAILURE = 'GET_USAGE_STATISTICS_FAILURE';